name: ci
on: push
jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout move-test
        uses: actions/checkout@v4
        with:
          path: move-test
      - name: Checkout stdlib
        uses: actions/checkout@v4
        with:
          repository: fortran-lang/stdlib
          path: stdlib
      - name: Checkout test-drive
        uses: actions/checkout@v4
        with:
          repository: fortran-lang/test-drive
          path: test-drive
      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 13
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: move-test/environment.yml
          cache-environment: true
          cache-downloads: true
      - name: Build stdlib
        working-directory: stdlib
        run: |
          cmake -B build --install-prefix=$PWD
          cmake --build build --parallel
          cmake --install build
          echo "PKG_CONFIG_PATH=$PWD/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: Build test-drive
        working-directory: test-drive
        run: |
          meson setup builddir --prefix=$(pwd) --libdir=lib
          meson install -C builddir
          echo "PKG_CONFIG_PATH=$PWD/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: Build move-test
        working-directory: move-test
        run: |
          meson setup builddir --prefix=$PWD --libdir=bin
          meson install -C builddir
      - name: Test move-test standalone
        working-directory: move-test
        run: ./bin/strexe
      - name: Test move-test with test-drive
        working-directory: move-test
        run: meson test -C builddir --verbose