name: ci
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 13
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Build
        run: |
          meson setup builddir --prefix=$PWD --libdir=bin
          meson install -C builddir
      - name: Test
        run: meson test -C builddir --verbose